name: Build firmware
on:
  push:
    branches:
      - master
jobs:
  Build-MMDVM-TNC:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: git submodule setup
        run: |
          git submodule init
          git submodule update
      - name: Install dependencies
        run: sudo apt install -qy git build-essential gcc-arm-none-eabi
      - name: make dvm
        run: make dvm
      - name: Archive built firmware
        uses: actions/upload-artifact@v3
        with:
          name: mmdvm_f4.hex
          path: bin/mmdvm_f4.hex
