name: Build firmware
on:
  push:
    branches:
      - master
jobs:
  Build-MMDVM-TNC:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: git submodule setup
        run: |
          git submodule init
          git submodule update
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Install dependencies
        run: sudo apt install -qy git build-essential gcc-arm-none-eabi
      - name: Update Config.h
        run: |
          echo "#define CONFIG_H
          #define EXTERNAL_OSC 12000000
          #define STM32F4_NUCLEO_MORPHO_HEADER
          #define SERIAL_SPEED    115200

          // Select the initial packet mode
          // 1 = 1200 bps AFSK AX.25
          // 2 = 9600 bps C4FSK IL2P
          #define INITIAL_MODE    2

          // TX Delay in milliseconds
          #define TX_DELAY        300

          // TX Tail in milliseconds
          #define	TX_TAIL		100

          // P-Persistence in x/255
          #define P_PERSISTENCE   63

          // Slot Time in milliseconds
          #define SLOT_TIME       100

          // Set Duplex, 1 for full duplex, 0 for simplex
          #define DUPLEX          0

          // Select use of serial debugging
          #define SERIAL_DEBUGGING

          // Baud rate for serial debugging.
          #define DEBUGGING_SPEED 38400

          // Set the receive level (out of 255)
          #define RX_LEVEL        128

          // Set the mode 1 transmit level (out of 255)
          #define MODE1_TX_LEVEL  128

          // Set the mode 2 transmit level (out of 255)
          #define MODE2_TX_LEVEL  128

          // Use pins to output the current mode via LEDs
          #define MODE_LEDS" > Config.h

      - name: Make output dir
        run: mkdir firmware
      - name: Build simplex firmware
        run: |
          make dvm
          cp bin/mmdvm_f4.hex firmware/mmdvm-f4-simplex.hex
          cp firmware/mmdvm-f4-simplex.hex firmware/mmdvm-f4-simplex-${{ env.sha_short }}.hex
      - name: Archive built firmware
        uses: actions/upload-artifact@v3
        with:
          name: mmdvm-f4-simplex.hex
          path: bin/mmdvm_f4.hex
      - name: Reconfigure duplex 1
        run: sed -i 's/DUPLEX          0/DUPLEX          1/g' Config.h
      - name: Build duplex firmware 
        run: |
          make clean
          make dvm
          cp bin/mmdvm_f4.hex firmware/mmdvm-f4-duplex.hex
          cp firmware/mmdvm-f4-duplex.hex firmware/mmdvm-f4-duplex-${{ env.sha_short }}.hex
      - name: Archive built firmware
        uses: actions/upload-artifact@v3
        with:
          name: mmdvm-f4-duplex.hex
          path: bin/mmdvm_f4.hex
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: mmdvm-tnc
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
          SOURCE_DIR: firmware
